### ISSUE TITLE
Memory leak on CapturePreview() call

### ISSUE THREAD

**Issue by x1125** [jonmol/gphoto2#1]
Thank you so much for your bindings, they're still working great! I've just discovered a memory leak, which is fixed by this patch I've wrote.
https://github.com/x1125/gphoto2/pull/1/files

**Comment by jonmol** [comment]
Hey, thanks for the patch and glad you had use for the code. Wrote the code for a small project I had that I never ended up finishing but figured it was better to post it as someone might have use for it
